# Generated by Django 6.0.2 on 2026-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('mood', models.CharField(choices=[('comfort', 'Comfort'), ('energizing', 'Energizing'), ('quick', 'Quick'), ('light', 'Light'), ('celebration', 'Celebration')], max_length=20)),
                ('prep_minutes', models.PositiveIntegerField(default=10)),
                ('cook_minutes', models.PositiveIntegerField(default=10)),
                ('ingredients', models.TextField(help_text='One ingredient per line')),
                ('steps', models.TextField(help_text='One step per line')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='recipes', to='recipes.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
